name: file_manager_view
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  dio: ^4.0.0
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  path: ^1.8.0
  cupertino_icons: ^1.0.2
  signale: ^0.0.6
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    
dependency_overrides:
  global_repository:
    path: /Users/nightmare/Desktop/nightmare-space/global_repository