name: file_manager_view
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  
  desktop_drop: ^0.3.3
  better_player: ^0.0.83
  shelf_static: ^1.1.1
  shelf_router: ^1.1.3
  url_launcher: ^6.1.8
  get: ^4.6.5
  dio: ^4.0.6
  global_repository:
    git: https://github.com/nightmare-space/global_repository
  path: ^1.8.2
  open_file: ^3.2.1
  cupertino_icons: ^1.0.5
  signale: ^0.0.8
  flutter_svg: ^1.1.6
  path_provider: ^2.0.12
  app_manager:
    git: https://github.com/nightmare-space/app_manager
  cross_file: 0.3.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    
dependency_overrides:
  fwfh_text_style: 2.22.8+1
  # global_repository:
  #   path: /Users/nightmare/Desktop/nightmare-space/global_repository